<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260201150148 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE report_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(50) NOT NULL, subject VARCHAR(255) DEFAULT NULL, parent_id INT DEFAULT NULL, thread_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_read BOOLEAN DEFAULT false NOT NULL, sender_id INT NOT NULL, assigned_admin_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D6244D7FF624B39D ON report_message (sender_id)');
        $this->addSql('CREATE INDEX IDX_D6244D7F19268419 ON report_message (assigned_admin_id)');
        $this->addSql('CREATE INDEX IDX_REPORT_CREATED_AT ON report_message (created_at)');
        $this->addSql('CREATE INDEX IDX_REPORT_STATUS ON report_message (status)');
        $this->addSql('ALTER TABLE report_message ADD CONSTRAINT FK_D6244D7FF624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE report_message ADD CONSTRAINT FK_D6244D7F19268419 FOREIGN KEY (assigned_admin_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE report_message DROP CONSTRAINT FK_D6244D7FF624B39D');
        $this->addSql('ALTER TABLE report_message DROP CONSTRAINT FK_D6244D7F19268419');
        $this->addSql('DROP TABLE report_message');
    }
}
