<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migration: Create user_session table for session tracking.
 *
 * This table tracks active user sessions for:
 * - Real-time active users count
 * - Session management (logout, expiry)
 * - Security monitoring
 */
final class Version20260201200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user_session table for session tracking';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE user_session (
            id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id INT NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            last_seen_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            ip VARCHAR(45) DEFAULT NULL,
            user_agent TEXT DEFAULT NULL,
            ended_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
            token_jti VARCHAR(255) DEFAULT NULL,
            PRIMARY KEY (id)
        )');

        $this->addSql('CREATE INDEX IDX_SESSION_USER ON user_session (user_id)');
        $this->addSql('CREATE INDEX IDX_SESSION_ACTIVE ON user_session (ended_at)');
        $this->addSql('CREATE INDEX IDX_SESSION_LAST_SEEN ON user_session (last_seen_at)');
        $this->addSql('CREATE INDEX IDX_SESSION_JTI ON user_session (token_jti)');

        $this->addSql('ALTER TABLE user_session ADD CONSTRAINT FK_USER_SESSION_USER FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');

        $this->addSql('COMMENT ON COLUMN user_session.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_session.last_seen_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN user_session.ended_at IS \'(DC2Type:datetime_immutable)\'');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_session DROP CONSTRAINT FK_USER_SESSION_USER');
        $this->addSql('DROP TABLE user_session');
    }
}
