<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260201185515 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE impersonation_activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, action VARCHAR(255) NOT NULL, path VARCHAR(500) DEFAULT NULL, method VARCHAR(10) DEFAULT NULL, details JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, session_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_IMP_ACT_SESSION ON impersonation_activity (session_id)');
        $this->addSql('CREATE INDEX IDX_IMP_ACT_CREATED ON impersonation_activity (created_at)');
        $this->addSql('ALTER TABLE impersonation_activity ADD CONSTRAINT FK_4000158A613FECDF FOREIGN KEY (session_id) REFERENCES impersonation_session (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE impersonation_activity DROP CONSTRAINT FK_4000158A613FECDF');
        $this->addSql('DROP TABLE impersonation_activity');
    }
}
