<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260201124314 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE account_action_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, handled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, message TEXT DEFAULT NULL, payload JSON DEFAULT NULL, user_id INT NOT NULL, handled_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B3C2C374FE65AF40 ON account_action_request (handled_by_id)');
        $this->addSql('CREATE INDEX IDX_AAR_USER ON account_action_request (user_id)');
        $this->addSql('CREATE INDEX IDX_AAR_STATUS ON account_action_request (status)');
        $this->addSql('CREATE INDEX IDX_AAR_TYPE ON account_action_request (type)');
        $this->addSql('CREATE INDEX IDX_AAR_CREATED_AT ON account_action_request (created_at)');
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(50) NOT NULL, metadata JSON DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_user_id INT DEFAULT NULL, target_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AUDIT_ACTOR ON audit_log (actor_user_id)');
        $this->addSql('CREATE INDEX IDX_AUDIT_TARGET ON audit_log (target_user_id)');
        $this->addSql('CREATE INDEX IDX_AUDIT_ACTION ON audit_log (action)');
        $this->addSql('CREATE INDEX IDX_AUDIT_CREATED_AT ON audit_log (created_at)');
        $this->addSql('CREATE TABLE email_verification_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C4995C675F37A13B ON email_verification_token (token)');
        $this->addSql('CREATE INDEX IDX_EVT_USER ON email_verification_token (user_id)');
        $this->addSql('CREATE INDEX IDX_EVT_TOKEN ON email_verification_token (token)');
        $this->addSql('CREATE INDEX IDX_EVT_EXPIRES_AT ON email_verification_token (expires_at)');
        $this->addSql('CREATE TABLE impersonation_session (id UUID NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, user_agent TEXT DEFAULT NULL, reason TEXT DEFAULT NULL, token_jti VARCHAR(100) NOT NULL, impersonator_id INT NOT NULL, target_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7AA23151C144FB6 ON impersonation_session (token_jti)');
        $this->addSql('CREATE INDEX IDX_IMP_IMPERSONATOR ON impersonation_session (impersonator_id)');
        $this->addSql('CREATE INDEX IDX_IMP_TARGET ON impersonation_session (target_user_id)');
        $this->addSql('CREATE INDEX IDX_IMP_JTI ON impersonation_session (token_jti)');
        $this->addSql('CREATE INDEX IDX_IMP_EXPIRES_AT ON impersonation_session (expires_at)');
        $this->addSql('CREATE INDEX IDX_IMP_ACTIVE ON impersonation_session (impersonator_id, revoked_at)');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, payload JSON NOT NULL, is_read BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, recipient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_NOTIF_RECIPIENT ON notification (recipient_id)');
        $this->addSql('CREATE INDEX IDX_NOTIF_READ ON notification (is_read)');
        $this->addSql('CREATE INDEX IDX_NOTIF_CREATED_AT ON notification (created_at)');
        $this->addSql('CREATE INDEX IDX_NOTIF_RECIPIENT_READ_DATE ON notification (recipient_id, is_read, created_at)');
        $this->addSql('CREATE TABLE password_reset_tokens (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token VARCHAR(255) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3967A2165F37A13B ON password_reset_tokens (token)');
        $this->addSql('CREATE INDEX IDX_3967A216A76ED395 ON password_reset_tokens (user_id)');
        $this->addSql('ALTER TABLE account_action_request ADD CONSTRAINT FK_B3C2C374A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE account_action_request ADD CONSTRAINT FK_B3C2C374FE65AF40 FOREIGN KEY (handled_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F5859B83FF FOREIGN KEY (actor_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F56C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE email_verification_token ADD CONSTRAINT FK_C4995C67A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE impersonation_session ADD CONSTRAINT FK_C7AA2315D1107CFF FOREIGN KEY (impersonator_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE impersonation_session ADD CONSTRAINT FK_C7AA23156C066AFE FOREIGN KEY (target_user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAE92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT FK_3967A216A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD date_inscription TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD date_derniere_connexion TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD is_email_verified BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD email_verified_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD is_suspended BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE "user" ADD suspended_until TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD suspension_reason TEXT DEFAULT NULL');
        $this->addSql('CREATE INDEX IDX_USER_DATE_INSCRIPTION ON "user" (date_inscription)');
        $this->addSql('CREATE INDEX IDX_USER_DERNIERE_CONNEXION ON "user" (date_derniere_connexion)');
        $this->addSql('CREATE INDEX IDX_USER_DELETED_AT ON "user" (deleted_at)');
        $this->addSql('CREATE INDEX IDX_USER_EMAIL_VERIFIED ON "user" (is_email_verified)');
        $this->addSql('CREATE INDEX IDX_USER_SUSPENDED ON "user" (is_suspended)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE account_action_request DROP CONSTRAINT FK_B3C2C374A76ED395');
        $this->addSql('ALTER TABLE account_action_request DROP CONSTRAINT FK_B3C2C374FE65AF40');
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F5859B83FF');
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F56C066AFE');
        $this->addSql('ALTER TABLE email_verification_token DROP CONSTRAINT FK_C4995C67A76ED395');
        $this->addSql('ALTER TABLE impersonation_session DROP CONSTRAINT FK_C7AA2315D1107CFF');
        $this->addSql('ALTER TABLE impersonation_session DROP CONSTRAINT FK_C7AA23156C066AFE');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAE92F8F78');
        $this->addSql('ALTER TABLE password_reset_tokens DROP CONSTRAINT FK_3967A216A76ED395');
        $this->addSql('DROP TABLE account_action_request');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE email_verification_token');
        $this->addSql('DROP TABLE impersonation_session');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE password_reset_tokens');
        $this->addSql('DROP INDEX IDX_USER_DATE_INSCRIPTION');
        $this->addSql('DROP INDEX IDX_USER_DERNIERE_CONNEXION');
        $this->addSql('DROP INDEX IDX_USER_DELETED_AT');
        $this->addSql('DROP INDEX IDX_USER_EMAIL_VERIFIED');
        $this->addSql('DROP INDEX IDX_USER_SUSPENDED');
        $this->addSql('ALTER TABLE "user" DROP date_inscription');
        $this->addSql('ALTER TABLE "user" DROP date_derniere_connexion');
        $this->addSql('ALTER TABLE "user" DROP deleted_at');
        $this->addSql('ALTER TABLE "user" DROP is_email_verified');
        $this->addSql('ALTER TABLE "user" DROP email_verified_at');
        $this->addSql('ALTER TABLE "user" DROP is_suspended');
        $this->addSql('ALTER TABLE "user" DROP suspended_until');
        $this->addSql('ALTER TABLE "user" DROP suspension_reason');
    }
}
